// <auto-generated />
using System;
using FinalApp.src.Shared.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalApp.Migrations
{
    [DbContext(typeof(IPearContext))]
    partial class IPearContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalApp.src.Data.Registros.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TelefonoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TelefonoId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("FinalApp.src.Data.Telefonos.Telefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ProductionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TelefonoCiudadEnsanblajeId")
                        .HasColumnType("int");

                    b.Property<int?>("TelefonoColorId")
                        .HasColumnType("int");

                    b.Property<int?>("TelefonoGamaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TelefonoCiudadEnsanblajeId");

                    b.HasIndex("TelefonoColorId");

                    b.HasIndex("TelefonoGamaId");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("FinalApp.src.Data.Telefonos.TelefonoCiudadEnsanblaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TelefonoCiudadEnsanblajes");
                });

            modelBuilder.Entity("FinalApp.src.Data.Telefonos.TelefonoColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TelefonoColores");
                });

            modelBuilder.Entity("FinalApp.src.Data.Telefonos.TelefonoGama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TelefonoGamas");
                });

            modelBuilder.Entity("FinalApp.src.Data.Registros.Registro", b =>
                {
                    b.HasOne("FinalApp.src.Data.Telefonos.Telefono", "Telefono")
                        .WithMany()
                        .HasForeignKey("TelefonoId");
                });

            modelBuilder.Entity("FinalApp.src.Data.Telefonos.Telefono", b =>
                {
                    b.HasOne("FinalApp.src.Data.Telefonos.TelefonoCiudadEnsanblaje", "TelefonoCiudadEnsanblaje")
                        .WithMany()
                        .HasForeignKey("TelefonoCiudadEnsanblajeId");

                    b.HasOne("FinalApp.src.Data.Telefonos.TelefonoColor", "TelefonoColor")
                        .WithMany()
                        .HasForeignKey("TelefonoColorId");

                    b.HasOne("FinalApp.src.Data.Telefonos.TelefonoGama", "TelefonoGama")
                        .WithMany()
                        .HasForeignKey("TelefonoGamaId");
                });
#pragma warning restore 612, 618
        }
    }
}
